channels:
  - rapidsai
  - nvidia
  - conda-forge

dependencies:
  - python=3.9
  - cudatoolkit=11.5
  - setuptools
  - cython>=0.29.14,<3.0.0a0
  - pytest
  - pytest-asyncio
  - dask
  - distributed
  - cupy
  - numba>=0.46
  - rmm
